services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - mvp-postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U mvp -d mvpdatabase"]
        interval: 10s
        timeout: 5s
        retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped

  notion-mcp:
    image: mcp/notion:latest
    container_name: notion-mcp
    environment:
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_MCP_AUTH_TOKEN: ${NOTION_MCP_AUTH_TOKEN}
      OPENAPI_MCP_HEADERS: |
        {"Authorization":"Bearer ${NOTION_TOKEN}","Notion-Version":"2022-06-28"}
    command: ["--transport","http","--port","3000","--auth-token","${NOTION_MCP_AUTH_TOKEN}"]
    ports:
      - "3000:3000"
    restart: unless-stopped


volumes:
  mvp-postgres-data:
  ollama_data:
