dependencies {
    implementation project(':core')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
}

sourceSets {
    main {
        java {
            srcDirs = ["$rootDir/src/main/java"]
            include "com/felipe/belo/mvp/infra/**"
        }
        resources {
            srcDirs = []
        }
    }
}
